server:
  port: 9112

spring:
  application:
    name: springcloud-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  security:
#    user:
#      name: admin
#      password: admin


# 服务端点检查
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: springcloud-admin.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

